### ISSUE TITLE
pvcam startup issue. 

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/microscope#76]
Just tried the primeBSI with microscope and pvcam  DLL version: 881. It fails with the output below. Not sure if this is a python3 issue or an updated dll issue but I definately got this to work when we first bought the cameras.

$ deviceserver ../test.py
2019-04-26 11:56:38,530:PVCamera:DEBUG:PID 7500: Debugging messages on.
2019-04-26 11:56:38,550:PVCamera:INFO:PID 7500: DLL version: 881
2019-04-26 11:56:38,550:PVCamera:INFO:PID 7500: Initializing b'PMUSBCam00'
2019-04-26 11:56:39,089:PVCamera:INFO:PID 7500: Failed to start device. Retrying in 5s.
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\microscope-0.2.0+dev-py3.7.egg\microscope\cameras\pvcam.py", line 1419, in initialize
    p.current
  File "C:\Python37\lib\site-packages\microscope-0.2.0+dev-py3.7.egg\microscope\cameras\pvcam.py", line 1149, in current
    return str(memoryview(self.raw).tobytes()) or ''
  File "C:\Python37\lib\site-packages\microscope-0.2.0+dev-py3.7.egg\microscope\cameras\pvcam.py", line 1142, in raw
    return self._query()
  File "C:\Python37\lib\site-packages\microscope-0.2.0+dev-py3.7.egg\microscope\cameras\pvcam.py", line 1074, in _query
    raise Exception('pvcam: parameter %s not supported in python.' % self.name)
Exception: pvcam: parameter PARAM_DD_INFO not supported in python.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\microscope-0.2.0+dev-py3.7.egg\microscope\deviceserver.py", line 140, in run
    self._device.initialize()
  File "C:\Python37\lib\site-packages\microscope-0.2.0+dev-py3.7.egg\microscope\cameras\pvcam.py", line 1424, in initialize
    if not err.message.startswith('pvcam error 49'):
AttributeError: 'Exception' object has no attribute 'message'

**Comment by mickp** [comment]
Fixed in #90.
